name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
      with: 
          fetch-depth: 0

          
    - name: Docker auth
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASS: ${{secrets.DOCKER_PASS}}
      run: |
        echo "Logging in Docker"
        docker login -u $DOCKER_USER -p $DOCKER_PASS

        
    - name: Build the Docker image
      run: |
        docker build --tag to1edo/docker-graphql:0.0.2 .
        
    - name: Push the Docker image
      run: |
        docker push to1edo/docker-graphql:0.0.2


        
